spring:
datasource:
#  driver-class-name: ${}
#  url: ${}
#  username: ${}
#  password: ${}

#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true

#  data:
#    redis:
#      host: localhost
#      port: 6379

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: TRACE
  org.springframework.security.web: TRACE