spring:
  datasource:
    driver-class-name: ${DRIVER_NAME}
    url: ${DRIVER_URL}
    username: ${DRIVER_USER_NAME}
    password: ${DRIVER_PASSWORD}

  profiles:
    active: local

#  data:
#    redis:
#      host: ${REDIS_HOST}
#      port: ${REDIS_PORT:6379}
#      timeout: 5000ms

server:
  port: 8080
  servlet:
    context-path: /nok-nok